# Generated by Django 2.0.3 on 2018-03-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created'], 'verbose_name': 'Violin Blog Entry', 'verbose_name_plural': 'Violin Blog Entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='recording',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
